In [23]:
# Importação das bibliotecas
import re
import pandas as pd
import numpy as np
import nltk

In [24]:
!pip install nltk
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk) (1.1.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk) (4.64.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk) (7.1.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.7/dist-packages (3.4.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.4.4)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.6)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.21.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.4.0)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.6.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.23.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (21.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.6)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.3)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.64.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.9.1)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (8.1.0)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.1.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.6.15)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)

In [25]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
df = pd.read_csv("https://raw.githubusercontent.com/viniciusrpb/cic0269_natural_language_processing/main/datasets/corpora/tweets_polarity_classification/twitter-2013train-A.txt", sep='\t', encoding = 'utf-8', names=['id','polarity','text'])
df

,id,polarity,text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...
...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden..."
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...

In [27]:
text_df = df['text']
text_df

0       Gas by my house hit $3.39!!!! I\u2019m going t...
1       Theo Walcott is still shit\u002c watch Rafa an...
2       its not that I\u2019m a GSP fan\u002c i just h...
3       Iranian general says Israel\u2019s Iron Dome c...
4       Tehran\u002c Mon Amour: Obama Tried to Establi...
                              ...
9679    RT @MNFootNg It's monday and Monday Night Foot...
9680    All I know is the road for that Lomardi start ...
9681    All Blue and White fam, we r meeting at Golden...
9682    @DariusButler28   Have a great game agaist Tam...
9683    I'm pisseeedddd that I missed Kid Cudi's show ...
Name: text, Length: 9684, dtype: object

In [28]:
# Tornar texto minúsculo
df['preprocessed_text'] = text_df.str.lower()
df

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas by my house hit $3.39!!!! i\u2019m going t...
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott is still shit\u002c watch rafa an...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,its not that i\u2019m a gsp fan\u002c i just h...
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general says israel\u2019s iron dome c...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran\u002c mon amour: obama tried to establi...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,rt @mnfootng it's monday and monday night foot...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,all i know is the road for that lomardi start ...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...","all blue and white fam, we r meeting at golden..."
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,@dariusbutler28 have a great game agaist tam...
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,i'm pisseeedddd that i missed kid cudi's show ...

In [29]:
# Fução para remover padrões
def remove_pattern(input_text, pattern):
  r = re.findall(pattern, input_text)
  for word in r:
    input_text = re.sub(word, "", input_text)

  return input_text

In [30]:
# Remover os rt
df['preprocessed_text'] = np.vectorize(remove_pattern)(df['preprocessed_text'], 'rt[\s]+') 
df

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas by my house hit $3.39!!!! i\u2019m going t...
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott is still shit\u002c watch rafa an...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,its not that i\u2019m a gsp fan\u002c i just h...
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general says israel\u2019s iron dome c...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran\u002c mon amour: obama tried to establi...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,@mnfootng it's monday and monday night footbal...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,all i know is the road for that lomardi staat ...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...","all blue and white fam, we r meeting at golden..."
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,@dariusbutler28 have a great game agaist tam...
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,i'm pisseeedddd that i missed kid cudi's show ...

In [31]:
# Remover @usuarios
df['preprocessed_text'] = np.vectorize(remove_pattern)(df['preprocessed_text'], '@[A-Za-z0-9]+') 
df

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas by my house hit $3.39!!!! i\u2019m going t...
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott is still shit\u002c watch rafa an...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,its not that i\u2019m a gsp fan\u002c i just h...
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general says israel\u2019s iron dome c...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran\u002c mon amour: obama tried to establi...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,it's monday and monday night football is on m...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,all i know is the road for that lomardi staat ...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...","all blue and white fam, we r meeting at golden..."
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,have a great game agaist tampa bay tonight.
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,i'm pisseeedddd that i missed kid cudi's show ...

In [32]:
# Remover links sites
df['preprocessed_text'] = np.vectorize(remove_pattern)(df['preprocessed_text'], 'http?:\/\/') 
df

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas by my house hit $3.39!!!! i\u2019m going t...
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott is still shit\u002c watch rafa an...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,its not that i\u2019m a gsp fan\u002c i just h...
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general says israel\u2019s iron dome c...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran\u002c mon amour: obama tried to establi...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,it's monday and monday night football is on m...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,all i know is the road for that lomardi staat ...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...","all blue and white fam, we r meeting at golden..."
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,have a great game agaist tampa bay tonight.
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,i'm pisseeedddd that i missed kid cudi's show ...

In [33]:
# Remover caracteres especiais, pontuação e numeros. Inclusive hashtag #
df['preprocessed_text'] = df['preprocessed_text'].str.replace('[^A-Za-z]', ' ') 
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas by my house hit i u m going t...
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott is still shit u c watch rafa an...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,its not that i u m a gsp fan u c i just h...
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general says israel u s iron dome c...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran u c mon amour obama tried to establi...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,it s monday and monday night football is on m...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,all i know is the road for that lomardi staat ...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...",all blue and white fam we r meeting at golden...
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,have a great game agaist tampa bay tonight
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,i m pisseeedddd that i missed kid cudi s show ...

In [34]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [35]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [36]:
# Remover stop_words
df['preprocessed_text'] = df['preprocessed_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))
df

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas house hit u going chapel hill sat
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott still shit u c watch rafa johnny ...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,u gsp fan u c hate nick diaz u wait february
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general says israel u iron dome u deal...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran u c mon amour obama tried establish tie...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,monday monday night football mind love footbal...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,know road lomardi staat tonight set record pre...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...",blue white fam r meeting golden corral dinner ...
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,great game agaist tampa bay tonight
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,pisseeedddd missed kid cudi show dallas trendi...

In [37]:
# Tokenizing dataframe

tokens = df['preprocessed_text'].apply(lambda x: x.split())
tokens

0          [gas, house, hit, u, going, chapel, hill, sat]
1       [theo, walcott, still, shit, u, c, watch, rafa...
2       [u, gsp, fan, u, c, hate, nick, diaz, u, wait,...
3       [iranian, general, says, israel, u, iron, dome...
4       [tehran, u, c, mon, amour, obama, tried, estab...
                              ...
9679    [monday, monday, night, football, mind, love, ...
9680    [know, road, lomardi, staat, tonight, set, rec...
9681    [blue, white, fam, r, meeting, golden, corral,...
9682           [great, game, agaist, tampa, bay, tonight]
9683    [pisseeedddd, missed, kid, cudi, show, dallas,...
Name: preprocessed_text, Length: 9684, dtype: object

In [38]:
# Lemmatization
nltk.download('omw-1.4')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [39]:
# Lemmatization
lemmatizer = WordNetLemmatizer()
df['preprocessed_text'] = df['preprocessed_text'].apply( lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))
df

,id,polarity,text,preprocessed_text
0,264183816548130816,positive,Gas by my house hit $3.39!!!! I\u2019m going t...,gas house hit u going chapel hill sat
1,263405084770172928,negative,Theo Walcott is still shit\u002c watch Rafa an...,theo walcott still shit u c watch rafa johnny ...
2,262163168678248449,negative,its not that I\u2019m a GSP fan\u002c i just h...,u gsp fan u c hate nick diaz u wait february
3,264249301910310912,negative,Iranian general says Israel\u2019s Iron Dome c...,iranian general say israel u iron dome u deal ...
4,262682041215234048,neutral,Tehran\u002c Mon Amour: Obama Tried to Establi...,tehran u c mon amour obama tried establish tie...
...,...,...,...,...
9679,103158179306807296,positive,RT @MNFootNg It's monday and Monday Night Foot...,monday monday night football mind love footbal...
9680,103157324096618497,positive,All I know is the road for that Lomardi start ...,know road lomardi staat tonight set record pre...
9681,100259220338905089,neutral,"All Blue and White fam, we r meeting at Golden...",blue white fam r meeting golden corral dinner ...
9682,104230318525001729,positive,@DariusButler28 Have a great game agaist Tam...,great game agaist tampa bay tonight
9683,100461938533863424,negative,I'm pisseeedddd that I missed Kid Cudi's show ...,pisseeedddd missed kid cudi show dallas trendi...